# Generated by Django 5.1.6 on 2025-04-24 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_subscription_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='description',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='payment.subscriptionplan'),
        ),
    ]
