# Generated by Django 5.2.3 on 2025-07-19 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the member was added')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the member is active in the farm')),
                ('farm', models.ForeignKey(help_text='The farm to which this member belongs', limit_choices_to={'role': 'farm'}, on_delete=django.db.models.deletion.CASCADE, related_name='farm_members', to=settings.AUTH_USER_MODEL)),
                ('farm_user', models.ForeignKey(help_text='The farm user associated with this farm', limit_choices_to={'role': 'farm_user'}, on_delete=django.db.models.deletion.CASCADE, related_name='member_farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['-created_at'],
                'unique_together': {('farm', 'farm_user')},
            },
        ),
    ]
