# Generated by Django 5.2.3 on 2025-09-10 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('flight', 'Flight Booking'), ('restaurant', 'Restaurant Booking'), ('spa', 'Spa Booking'), ('birthday', 'Birthday Booking'), ('concert', 'Concert Tickets Booking'), ('hotel', 'Hotel Reservation')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('booking_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
