# Generated by Django 5.2.3 on 2025-09-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
