# Generated by Django 5.2.3 on 2025-06-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0006_rename_name_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
