# Generated by Django 5.2.3 on 2025-07-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0009_customuser_is_verified_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('consultant', 'Consultant'), ('farm_user', 'Farm User')], default='user', max_length=10),
        ),
    ]
