# Generated by Django 5.2.3 on 2025-07-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0011_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('farm', 'Farm'), ('consultant', 'Consultant'), ('farm_user', 'Farm User')], default='user', max_length=10),
        ),
    ]
