# Generated by Django 5.2.3 on 2025-08-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0014_rename_name_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['email'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
