# Generated by Django 5.2.3 on 2025-08-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0015_alter_customuser_options_userprofile_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='secret_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
