# Generated by Django 5.2.3 on 2025-08-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0016_otp_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
