# Generated by Django 5.2.3 on 2025-07-19 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('bottle_size', models.DecimalField(blank=True, decimal_places=2, help_text='Size of each bottle in liters or specified unit', max_digits=10, null=True)),
                ('number_of_bottles', models.PositiveIntegerField(default=1, help_text='Number of bottles prepared')),
                ('hospital_solids', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage or weight of solids in hospital milk', max_digits=10, null=True)),
                ('hospital_milk_volume', models.DecimalField(blank=True, decimal_places=2, help_text='Volume of hospital milk used in liters or specified unit', max_digits=10, null=True)),
                ('desired_solids_content', models.DecimalField(blank=True, decimal_places=2, help_text='Desired solids content percentage for the milk mixture', max_digits=10, null=True)),
                ('pounds_of_water', models.DecimalField(blank=True, decimal_places=2, help_text='Pounds of water used in the mixture', max_digits=10, null=True)),
                ('pounds_of_milk_replacer', models.DecimalField(blank=True, decimal_places=2, help_text='Pounds of milk replacer used in the mixture', max_digits=10, null=True)),
                ('solids_hospital_milk', models.DecimalField(blank=True, decimal_places=2, help_text='Weight of solids contributed by hospital milk', max_digits=10, null=True)),
                ('hospital_milk_used', models.DecimalField(blank=True, decimal_places=2, help_text='Amount of hospital milk used in pounds or specified unit', max_digits=10, null=True)),
                ('user', models.ForeignKey(help_text='The user who created this milk preparation record', on_delete=django.db.models.deletion.CASCADE, related_name='milk_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Milk History',
                'verbose_name_plural': 'Milk Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
