# Generated by Django 5.2.3 on 2025-07-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkhistory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkhistory',
            name='total_volume',
            field=models.CharField(blank=True, help_text='Total volume of the milk mixture prepared', max_length=400, null=True),
        ),
    ]
